name: is_firebase_test_lab_activated
description: A flutter plugin to know if Firebase Test Lab is activated
version: 2.0.0
homepage: https://github.com/RicardoRB/isfirebasetestlabactivated

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ricardorb.is_firebase_test_lab_activated
        pluginClass: IsFirebaseTestLabActivatedPlugin
      ios:
        pluginClass: IsFirebaseTestLabActivatedPlugin
